### ISSUE TITLE
Handle original_epub format from calibre

### ISSUE THREAD

**Issue by mduplouy** [mduplouy/silex-cops#21]
Exception raised when encoutering this format

**Comment by mduplouy** [comment]
@fufroma should be ok now ;)

**Comment by fufroma** [comment]
Yop,

Je suis bien sur la bonne version :
commit cc86f5a6a79c2e0c1a7563844b87fc115fd45737
Author: Mathieu Duplouy <mathieu.duplouy@gmail.com>
Date:   Sun Jan 11 13:58:29 2015 +0100

    ORIGINAL_EPUB handling


J'ai bien clear-cache


Et toutefois :

[Mon Jan 12 13:27:58 2015] [error] [client 212.85.130.11] PHP Fatal error:
Class 'Cops\\Model\\BookFile\\Adapter\\Original_epub' not found in
/home/fufroma/silex-cops/app/cops/Cops/Model/BookFile/BookFileFactory.php
on line 68, referer: http://cops.isoodon.org/index.php/current/fr/

**Comment by mduplouy** [comment]
should be ok now ;)

**Comment by mduplouy** [comment]
Validated as working fine
